# fly.toml app configuration file generated for examples-holy-star-6994 on 2024-09-23T19:29:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'examples-holy-star-6994'
primary_region = 'cdg'

[build]

[env]
  PORT = "3000"
  MONGODB_URI = "mongodb+srv://tomasrl18:oWCHSpBBDanosLBp@cluster0.krk9q.mongodb.net/noteApp?retryWrites=true&w=majority&appName=Cluster0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
